version: "3.3"
services:
  core:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - core_develop.env

  database:
    image: postgres:latest
    # Not necessary for compose, but is necessary for expose database to app running in intellij
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: test
      POSTGRES_DB: coredb